import { Modelo } from '@boom/modelos/modelo';
import { Empresa } from '../empresa';
import { Escolaridade } from './escolaridade';
import { TipoContrato } from './tipoContrato';
import { Situacao } from './situacao';
import { Genero } from './genero';

export class Vaga extends Modelo {
    empresa: Empresa;
    url?: string;
    nomeDaFuncao: string;
    quantidadeVagas: number;
    vagaSigilosa: boolean;
    dataLimiteSelecao: Date;
    dataLimiteIntegracao: Date;
    situacao: Situacao;
    atribuicaoSumaria: string;
    atividadesTipicas: string;
    atividadesEventuais: string;
    nivelAutoridadeResponsabilidade: string;
    habilidadesNecessarias: string;
    requisitosBasicos: string;
    requisitosDesejaveis: string;
    escolaridade: Escolaridade;
    cursosObrigatorios: string;
    tipoContrato: TipoContrato;
    cargaHorariaSemanal: number;
    remuneracao: string;
    informaComissoesBonus: boolean;
    comissoesBonus: string;
    valeAlimentacao: boolean;
    valeTransporte: boolean;
    valeRefeicao: boolean;
    segundaFeiraInicio: string;
    segundaFeiraFim: string;
    tercaFeiraInicio: string;
    tercaFeiraFim: string;
    quartaFeiraInicio: string;
    quartaFeiraFim: string;
    quintaFeiraInicio: string;
    quintaFeiraFim: string;
    sextaFeiraInicio: string;
    sextaFeiraFim: string;
    sabadoInicio: string;
    sabadoFim: string;
    domingoInicio: string;
    domingoFim: string;
    informacoesRock: string;
    genero: Genero;
    dataInclusao: Date;
    sequencialEmpresa: number;
}